# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mole_tracker_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mole_tracker_app
pod 'expanding-collection'

  target 'mole_tracker_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mole_tracker_appUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
